# DigitalOcean App Platform Configuration
name: performance-dashboard
services:
  # Backend API + Worker + Scheduler (combined service)
  - name: api
    source_dir: /
    github:
      repo: syatt-io/performance-dashboard
      branch: main
      deploy_on_push: true
    build_command: npm ci && npx prisma migrate deploy && npm run build
    run_command: npm run start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: professional-xs  # Increased for Lighthouse operations
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        type: SECRET
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        type: SECRET
        scope: RUN_TIME
      - key: ENCRYPTION_KEY
        type: SECRET
        value: YOUR_32_CHAR_ENCRYPTION_KEY_REPLACE_THIS
      - key: PAGESPEED_API_KEY
        type: SECRET
        value: YOUR_PAGESPEED_API_KEY
      - key: WEBPAGETEST_API_KEY
        type: SECRET
        value: YOUR_WEBPAGETEST_API_KEY
      - key: ALLOWED_ORIGINS
        value: https://performance-dashboard-p7pf5.ondigitalocean.app
      - key: NEXT_PUBLIC_API_URL
        value: https://performance-dashboard-p7pf5.ondigitalocean.app

# Database Component
databases:
  - name: db
    engine: PG
    version: "15"
    size: basic
    num_nodes: 1